spring:
  application:
    name: metric-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true

server:
  port: 8888

management:
  server:
    port: 8080

endpoints:
  restart:
    enabled: true

logging:
  level:
    root: INFO
    org.apache.zookeeper.ClientCnxn: WARN